#!/usr/bin/env node
// Generates src/version.mjs from package.json's "version" field.
//
// Why a generated file instead of reading package.json at runtime: a
// packaged SEA binary has no package.json on disk to read (see
// src/assets.mjs's own module-loading note), and the version only needs to
// be a literal string baked in at build time either way. Since
// src/version.mjs is a plain local module like any other, the hand-rolled
// bundler in scripts/build-sea-bundle.mjs inlines it automatically — no
// special-casing needed in the SEA asset map.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_PATH = path.join(projectRoot, 'src', 'version.mjs');

async function render() {
  const pkg = JSON.parse(await fs.readFile(path.join(projectRoot, 'package.json'), 'utf8'));
  if (!pkg.version) throw new Error('package.json has no "version" field.');
  return [
    '// Generated by scripts/gen-version.mjs from package.json — do not edit by hand.',
    `export const VERSION = ${JSON.stringify(pkg.version)};`,
    ''
  ].join('\n');
}

async function main() {
  const check = process.argv.includes('--check');
  const pkg = JSON.parse(await fs.readFile(path.join(projectRoot, 'package.json'), 'utf8'));
  const rendered = await render();

  if (check) {
    let existing;
    try {
      existing = await fs.readFile(OUT_PATH, 'utf8');
    } catch (error) {
      if (error.code === 'ENOENT') existing = null;
      else throw error;
    }
    if (existing !== rendered) {
      console.error('src/version.mjs is out of date. Run: node scripts/gen-version.mjs');
      process.exit(1);
    }
    console.log('src/version.mjs is current.');
    return;
  }

  await fs.writeFile(OUT_PATH, rendered);
  console.log(`Wrote src/version.mjs (${pkg.version}).`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
